### ISSUE TITLE
DBToolsUnitTest - one failed test

### ISSUE THREAD

**Issue by tshao4** [The-Student-Cookbook/The-Student-Cookbook#10]
Output: 
junit.framework.AssertionFailedError: expected:<[Title: recipe1,
ID: 1,
BigOvenId: 0,
Bases: base1,
Cuisines: cuisine1,
Ingredients: 1.0 ingredient1-1:unit ingredient1-1, 2.0 ingredient1-2:unit ingredient1-2,
Tools: tool11: tool11:description, tool12: tool12:description,
Technique:
Cooktime: 30,
Preptime: 10,
Image URL: recipe1:url,
Instructions: recipe1:instructions
]> 
but was:
<[Title: recipe1,
ID: 1,
BigOvenId: 0,
Bases: base1,
Cuisines: cuisine1,
Ingredients: 1.0 ingredient1-1:unit ingredient1-1, 2.0 ingredient1-2:unit ingredient1-2,
Tools: tool11: tool11:description, tool12: tool12:description,
Technique: technique11,
Cooktime: 30,
Preptime: 10,
Image URL: recipe1:url,
Instructions: recipe1:instructions
]>
at cs506.studentcookbook.DBToolsUnitTest.testPinnedRecipes(DBToolsUnitTest.java:901)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:555)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1853)

**Comment by cquagliana** [comment]
Steve, can you look at this?

**Comment by cquagliana** [comment]
It's the ones on line 901 and 906.
